### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'

### ISSUE THREAD

**Issue by prof7bit** [EugenWiens/vscode-bitbake#23]
Today I opened a recipe and code threw this error log in the console:
````
error: parsing all recipes is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
error: scanning of project is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:89
                throw error;
                ^

Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at BitBakeProjectScanner.executeCommandInBitBakeEnvironment (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:287:12)
    at BitBakeProjectScanner.scanAvailableLayers (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:118:27)
    at BitBakeProjectScanner.rescanProject (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:78:26)
    at Timeout.setTimeout [as _onTimeout] (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/server.js:25:31)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 08:55:47] Connection to server got closed. Server will restart.
error: parsing all recipes is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
error: scanning of project is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:89
                throw error;
                ^

Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at BitBakeProjectScanner.executeCommandInBitBakeEnvironment (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:287:12)
    at BitBakeProjectScanner.scanAvailableLayers (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:118:27)
    at BitBakeProjectScanner.rescanProject (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:78:26)
    at Timeout.setTimeout [as _onTimeout] (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/server.js:25:31)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 08:55:48] Connection to server got closed. Server will restart.
error: parsing all recipes is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
error: scanning of project is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:89
                throw error;
                ^

Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at BitBakeProjectScanner.executeCommandInBitBakeEnvironment (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:287:12)
    at BitBakeProjectScanner.scanAvailableLayers (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:118:27)
    at BitBakeProjectScanner.rescanProject (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:78:26)
    at Timeout.setTimeout [as _onTimeout] (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/server.js:25:31)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 08:55:49] Connection to server got closed. Server will restart.
error: parsing all recipes is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
error: scanning of project is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:89
                throw error;
                ^

Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at BitBakeProjectScanner.executeCommandInBitBakeEnvironment (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:287:12)
    at BitBakeProjectScanner.scanAvailableLayers (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:118:27)
    at BitBakeProjectScanner.rescanProject (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:78:26)
    at Timeout.setTimeout [as _onTimeout] (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/server.js:25:31)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Info  - 08:55:49] Connection to server got closed. Server will restart.
error: parsing all recipes is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
error: scanning of project is abborted: Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:89
                throw error;
                ^

Error: ENOENT: no such file or directory, open 'null/executeBitBakeCmd.sh'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at BitBakeProjectScanner.executeCommandInBitBakeEnvironment (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:287:12)
    at BitBakeProjectScanner.scanAvailableLayers (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:118:27)
    at BitBakeProjectScanner.rescanProject (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/BitBakeProjectScanner.js:78:26)
    at Timeout.setTimeout [as _onTimeout] (/home/bernd/.vscode/extensions/EugenWiens.bitbake-1.0.1/server/server.js:25:31)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[Error - 08:55:50] Connection to server got closed. Server will not be restarted.
````

**Comment by EugenWiens** [comment]
Is it possible for you to check if the file `executeBtBakeCmd.sh` was created successfully ? You can find this file in the root of your `yocto` Project.

**Comment by EugenWiens** [comment]
Any news on this topic ?

**Comment by youurayy** [comment]
While maybe not directly related, may I suggest (perhaps adding an option for) _not_ automatically creating the `executeBitBakeCmd.sh`?  E.g. I'm using Yocto and bitbake is not even in that directory + I'm always running bitbake from command line.

**Comment by EugenWiens** [comment]
Hi,
This file is used by the vscode-bitbake plugin to execute bitbake commands.
This commands are helpful to get layer list or parse yocto to detect syntax
errors.
Does this file confused you. Should this file moved to the plugin build
folder?



Juraj Vitko <notifications@github.com> schrieb am Mo., 26. März 2018, 06:12:

**Comment by EugenWiens** [comment]
@youurayy wold it be better when the file is moved to the `vscode-bitbake` folder ?

**Comment by youurayy** [comment]
yes, I believe an extension should not modify the filesystem of the user project as a side effect in any way.

**Comment by EugenWiens** [comment]
@EugenRn: I will add this Feature and to track this I added an Issue #25
